general:
  name: "poisson"
  num_steps: 50

likelihood:
  type: "poisson"
  std : 0.1
  scale: true
  sample_ratio: 0.25

utility:
  use_utility_sf: true
  utility_sf_sigma: 90

paths:
  model_path: "models/version_14896865_uq/checkpoints/epoch=7846-step=376656.ckpt"
  data_path: "/pscratch/sd/z/zhantao/inxs_steering_production/experiment_data/summarized_neutron_data_w_bkg_260meV_ML.pt"
  output_path: "/pscratch/sd/z/zhantao/inxs_steering_production/benchmarks"
  raw_mask_path: "/pscratch/sd/z/zhantao/inxs_steering_production/mask/La2NiO4_bool_by_angles"
  memmap_mask_path: "/pscratch/sd/z/zhantao/inxs_steering_production/mask/memmap_mask"
  spinw_data_path: "/pscratch/sd/z/zhantao/inxs_steering/SpinW_data/summarized_AFM_data_2023Sep13.pt"